# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4652be8fd0b3e626a2d5875e6ac07c760c4c07378992542b17d34b96d3a16da7d74fdf52e5e99c7ebc91563eb2abd7b1729d550af4c1bcc935dbe0b55938d6f1

test:
  secret_key_base: c7c5f24792ea633ecc9e55c5824d98c6baf04529097dfaf64dcd158c19607fb43f9ddff8c700882be971b4425d42767bff371199a21457c4a0ce23ca84fcb7e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
